import React, { useEffect, useState, useCallback } from "react";
import complianceApi from "../../api/complianceApi";
import SectionHeader from "../../components/shared/SectionHeader";
import AlertBanner from "../../components/shared/AlertBanner";
import GenericTable from "../../components/shared/GenericTable";
import Spinner from "../../components/shared/Spinner";
import { parseApiError } from "../../utils/apiErrorParser";

const SCOPE_OPTIONS = ["Compliance", "Student", "Course", "Exam", "Attendance"];
const STATUS_OPTIONS = ["GENERATED", "ARCHIVED"];

function readRoleFromStorage() {
  try {
    const raw = localStorage.getItem("edu_user");
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    return parsed?.role || null;
  } catch {
    return null;
  }
}

function statusBadgeClass(status) {
  switch ((status || "").toUpperCase()) {
    case "GENERATED": return "bg-green-100 text-green-800";
    case "ARCHIVED":  return "bg-gray-200 text-gray-700";
    default:          return "bg-gray-100 text-gray-700";
  }
}

function prettyMetrics(metrics) {
  if (!metrics) return null;
  try {
    const obj = JSON.parse(metrics);
    return obj && typeof obj === "object" ? obj : null;
  } catch {
    return null;
  }
}

export default function ReportsPage() {
  const role = readRoleFromStorage();
  const canWrite = role === "COMPLIANCE_OFFICER" || role === "EDUCATION_BOARD_OFFICER";
  const canDelete = role === "COMPLIANCE_OFFICER";

  const [rows, setRows] = useState([]);
  const [filter, setFilter] = useState({ scope: "", schoolId: "" });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const [genForm, setGenForm] = useState({
    scope: "Compliance",
    title: "",
    schoolId: "",
    description: "",
  });
  const [generating, setGenerating] = useState(false);
  const [expandedId, setExpandedId] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const params = {};
      if (filter.scope) params.scope = filter.scope;
      if (filter.schoolId) params.schoolId = filter.schoolId;
      const res = await complianceApi.fetchReports(params);
      const list = res?.data?.data ?? res?.data ?? [];
      setRows(Array.isArray(list) ? list : []);
    } catch (err) {
      setError(parseApiError(err));
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => { load(); }, [load]);

  const onFilterChange = (e) => {
    const { name, value } = e.target;
    setFilter((f) => ({ ...f, [name]: value }));
  };

  const onGenFormChange = (e) => {
    const { name, value } = e.target;
    setGenForm((f) => ({ ...f, [name]: value }));
  };

  const onGenerate = async (e) => {
    e.preventDefault();
    setError("");
    setSuccess("");
    setGenerating(true);
    try {
      await complianceApi.generateReport(genForm);
      setSuccess(`${genForm.scope} report generated.`);
      setGenForm({ scope: "Compliance", title: "", schoolId: "", description: "" });
      load();
    } catch (err) {
      setError(parseApiError(err));
    } finally {
      setGenerating(false);
    }
  };

  const onArchive = async (row) => {
    try {
      const newStatus = row.status === "ARCHIVED" ? "GENERATED" : "ARCHIVED";
      await complianceApi.updateReport(row.id, { status: newStatus });
      setSuccess(`Report #${row.id} status set to ${newStatus}.`);
      load();
    } catch (err) {
      setError(parseApiError(err));
    }
  };

  const onDelete = async (id) => {
    if (!window.confirm("Delete this report?")) return;
    try {
      await complianceApi.deleteReport(id);
      setSuccess("Report deleted.");
      load();
    } catch (err) {
      setError(parseApiError(err));
    }
  };

  const columns = [
    { key: "id", label: "ID" },
    { key: "scope", label: "Scope" },
    { key: "title", label: "Title" },
    { key: "schoolId", label: "School" },
    { key: "generatedByEmail", label: "Generated By" },
    {
      key: "generatedDate",
      label: "Generated",
      render: (row) => row.generatedDate ? new Date(row.generatedDate).toLocaleString() : "—",
    },
    {
      key: "status",
      label: "Status",
      render: (row) => (
        <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${statusBadgeClass(row.status)}`}>
          {row.status}
        </span>
      ),
    },
    {
      key: "actions",
      label: "Actions",
      render: (row) => (
        <div className="flex flex-wrap gap-1">
          <button
            type="button"
            onClick={() => setExpandedId((id) => id === row.id ? null : row.id)}
            className="px-2 py-1 text-xs bg-blue-50 text-blue-700 rounded hover:bg-blue-100"
          >
            {expandedId === row.id ? "Hide" : "View"}
          </button>
          {canWrite && (
            <button
              type="button"
              onClick={() => onArchive(row)}
              className="px-2 py-1 text-xs bg-gray-100 text-gray-700 rounded hover:bg-gray-200"
            >
              {row.status === "ARCHIVED" ? "Restore" : "Archive"}
            </button>
          )}
          {canDelete && (
            <button
              type="button"
              onClick={() => onDelete(row.id)}
              className="px-2 py-1 text-xs bg-red-50 text-red-700 rounded hover:bg-red-100"
            >
              Delete
            </button>
          )}
        </div>
      ),
    },
  ];

  const expandedRow = expandedId != null ? rows.find((r) => r.id === expandedId) : null;
  const expandedMetrics = expandedRow ? prettyMetrics(expandedRow.metrics) : null;

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="max-w-7xl mx-auto">
        <SectionHeader
          title="Reports"
          subtitle="Persisted analytics reports across scopes (Compliance, Student, Course, Exam, Attendance)."
        />

        <AlertBanner type="error" message={error} onClose={() => setError("")} />
        <AlertBanner type="success" message={success} onClose={() => setSuccess("")} />

        {/* Generate Report */}
        {canWrite && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-6">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">Generate Report Snapshot</h3>
            <form onSubmit={onGenerate} className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Scope *</label>
                <select
                  name="scope"
                  value={genForm.scope}
                  onChange={onGenFormChange}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                >
                  {SCOPE_OPTIONS.map((s) => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Title</label>
                <input
                  type="text"
                  name="title"
                  value={genForm.title}
                  onChange={onGenFormChange}
                  placeholder="auto if empty"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">School ID</label>
                <input
                  type="text"
                  name="schoolId"
                  value={genForm.schoolId}
                  onChange={onGenFormChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <button
                  type="submit"
                  disabled={generating}
                  className="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                >
                  {generating ? "Generating…" : "Generate"}
                </button>
              </div>
              <div className="md:col-span-4">
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea
                  name="description"
                  value={genForm.description}
                  onChange={onGenFormChange}
                  rows={2}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <p className="md:col-span-4 text-xs text-gray-500">
                Compliance / Rule scope auto-aggregates live rule counts. Other scopes save an empty snapshot
                you can edit later via API.
              </p>
            </form>
          </div>
        )}

        {/* Filters */}
        <div className="bg-white rounded-lg shadow-md p-4 mb-6 grid grid-cols-1 md:grid-cols-3 gap-3">
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">Scope</label>
            <select
              name="scope"
              value={filter.scope}
              onChange={onFilterChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
            >
              <option value="">All</option>
              {SCOPE_OPTIONS.map((s) => <option key={s} value={s}>{s}</option>)}
              {STATUS_OPTIONS.length === 0 ? null : null}
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">School ID</label>
            <input
              type="text"
              name="schoolId"
              value={filter.schoolId}
              onChange={onFilterChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
            />
          </div>
          <div className="flex items-end">
            <button
              type="button"
              onClick={() => setFilter({ scope: "", schoolId: "" })}
              className="w-full px-4 py-2 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 text-sm"
            >
              Clear Filters
            </button>
          </div>
        </div>

        {/* Table */}
        <div className="bg-white rounded-lg shadow-md p-4">
          {loading ? (
            <Spinner />
          ) : (
            <GenericTable
              columns={columns}
              data={rows}
              emptyMessage="No reports found."
            />
          )}
        </div>

        {/* Expanded report details */}
        {expandedRow && (
          <div className="bg-white rounded-lg shadow-md p-6 mt-4">
            <div className="flex items-start justify-between mb-3">
              <div>
                <h3 className="text-lg font-semibold text-gray-800">
                  {expandedRow.title}
                  <span className="ml-2 text-sm font-normal text-gray-500">#{expandedRow.id}</span>
                </h3>
                <p className="text-sm text-gray-500">
                  {expandedRow.scope} · generated{" "}
                  {expandedRow.generatedDate ? new Date(expandedRow.generatedDate).toLocaleString() : ""}
                </p>
              </div>
              <button
                type="button"
                onClick={() => setExpandedId(null)}
                className="text-sm text-gray-500 hover:text-gray-700"
              >
                Close
              </button>
            </div>

            {expandedRow.description && (
              <p className="text-sm text-gray-700 mb-3">{expandedRow.description}</p>
            )}

            {expandedMetrics ? (
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {Object.entries(expandedMetrics).map(([k, v]) => (
                  <div key={k} className="bg-gray-50 rounded p-3">
                    <div className="text-xs text-gray-500 uppercase tracking-wide">{k}</div>
                    <div className="text-lg font-semibold text-gray-800">{String(v)}</div>
                  </div>
                ))}
              </div>
            ) : (
              <pre className="bg-gray-50 rounded p-3 text-xs text-gray-700 overflow-x-auto">
                {expandedRow.metrics || "(no metrics)"}
              </pre>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
